spring.application.name=saas_facturation

spring.datasource.url=jdbc:h2:file:{{url-repo-data}};AUTO_SERVER=TRUE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

spring.jpa.defer-datasource-initialization=true
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.sql.init.mode=always

spring.h2.console.enabled=true
spring.h2.console.path=/h2

#Variables utilisées pour le stockage de document(facture, devis)
app.storage.type=local
app.storage.local-path=data/documents

#Variables utilisées pour l'insertion de l'entreprise emettrice des documents (devis, facture)
app.company.name=Klimafact SARL
app.company.tagline=Climatisation & Chauffage
app.company.address=12 rue de la Paix, 69001 Lyon
app.company.siret=000 000 000 00000
app.company.tva-number=FR00000000000
app.company.email=contact@klimafact.fr
app.company.phone=+33 4 00 00 00 00
app.company.iban=FR76 0000 0000 0000 0000 0000 000